### ISSUE TITLE
fuse: missing mountpoint parameter

### ISSUE THREAD

**Issue by olvier** [hotio/docker-mergerfs#5]
hey folks,
hey @hotio,

i'm totally in love with docker and so i want to use mergerfs in docker, too :)

now i am stuck with an error fuse: missing mountpoint parameter

i added container with following parameters:

`sudo docker run \ --name=hotio-mergerfs-cli \ 
--env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \ 
--env=BRANCHES=/source1:/source2 \ 
--env=MOUNTPOINT=/mounts/MergerFS \ 
--env=TZ=Europe/Berlin \ 
--volume=/volume1/docker/mergerfs/config:/config \ 
--volume=/volume2/Video2/mergerfs/test1:/source1 \ 
--volume=/volume2/Video2/mergerfs/test2:/source2 \ 
--volume=/volume2/Video2/mergerfs/movies:/mounts/MergerFS:shared \ 
--cap-add SYS_ADMIN \ 
--network=bridge \ 
--privileged \ 
--restart=no \ 
--device /dev/fuse \ 
--label org.label-schema.build-date="2020-06-06T10:11:32Z" \ 
--label org.label-schema.vcs-ref="8090586b1a7a" \ 
--label maintainer="hotio" \ 
--label org.label-schema.vcs-url="https://github.com/hotio/docker-mergerfs.git" \ 
--label org.label-schema.schema-version="1.0" \ 
--log-driver=db \ 
--detach=true \ 
--security-opt apparmor:unconfined \ 
hotio/mergerfs:latest`

![image](https://user-images.githubusercontent.com/13106409/87086605-1d109200-c232-11ea-9150-70521a9ddd3c.png)

does somebody see my problem? and also has a solution for it?

**Comment by hotio** [comment]
Please read the readme, you're using old instructions, the default entrypoint is mergerfs.

**Comment by olvier** [comment]
Which readme? I haven't found any here. Only 2 threads on the world wide web, which are different to each other's handling. So, for me, a readme is sth like linuxserver.io's docker-container, where possible parameters are listed.

Please help me to find your mentioned readme :)

**Comment by hotio** [comment]
https://github.com/hotio/docker-mergerfs/blob/master/README.md

I think you don't seem to grasp how to implement this container into your scripts since you are expecting 'parameters'?

**Comment by olvier** [comment]
I don't know how to feed the container with the needed 'paramteters' like mounts/binds, environment variables and so on.

I never had a container with this little information, how to use it. For example rar2fs is kinda equal to yours, also with the need to mount volumes with :shared parameter.

https://github.com/zimme/docker-rar2fs
But there are some examples which 'parameters' to use. ("Usage" for example). This is what I have 'expected' here, too. W/o I just don't know how to use your container ;)

But maybe it's just a lack of knowledge or skill for my own.

**Comment by hotio** [comment]
You would just use it as you'd use mergerfs outside of docker, no point in me copy/pasting the entire mergerfs documentation...

**Comment by olvier** [comment]
Can somebody help here? Or posting his compose or 'docker run' sequence? I guess there are still some volume binds or mounts or other parameters, which I do not know, needed.

Would be awesome!

**Comment by shanehughes1990** [comment]
@olvier, My working compose for this container, combines local_media and gcrypt_media volumes and merges them to /data/media can be seen on the host. You will obviously need to setup the networks and the variables. I also have a depends_on rclone but change as you would need.
```
  mergerfs:
    image: hotio/mergerfs
    container_name: $STACK-mergerfs
    restart: always
    depends_on:
      - rclone
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse"
    security_opt:
      - "apparmor:unconfined"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    command: /data/local_media:/data/gcrypt_media /data/media -o rw,use_ino,allow_other,func.getattr=newest,category.action=all,category.create=ff,cache.files=auto-full
    volumes:
      - $LOCAL_MEDIA:/data/local_media
      - $GCRYPT_MEDIA:/data/gcrypt_media
      - $MEDIA:/data/media:shared
    networks:
      - ext_net
      - int_net
```
